-- CreateTable
CREATE TABLE "users" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "displayName" TEXT,
    "email" TEXT,
    "password" TEXT,
    "zipCode" TEXT,
    "name" TEXT,
    "avatar" TEXT,
    "email_change" TEXT,
    "emailVisibility" BOOLEAN NOT NULL DEFAULT false,
    "email_change_sent_at" DATETIME,
    "email_change_token_new" TEXT,
    "email_change_confirm_status" INTEGER DEFAULT 0,
    "email_change_token_current" TEXT DEFAULT '',
    "email_confirmed_at" DATETIME,
    "reauthentication_token" TEXT DEFAULT '',
    "reauthentication_sent_at" DATETIME,
    "recovery_token" TEXT,
    "recovery_sent_at" DATETIME,
    "is_super_admin" BOOLEAN NOT NULL DEFAULT false,
    "is_sso_user" BOOLEAN NOT NULL DEFAULT true,
    "is_anonymous" BOOLEAN NOT NULL DEFAULT false,
    "phone" TEXT,
    "phone_change" TEXT DEFAULT '',
    "phone_change_token" TEXT DEFAULT '',
    "phone_change_sent_at" DATETIME,
    "phone_confirmed_at" DATETIME,
    "browser" TEXT,
    "device" TEXT,
    "online" BOOLEAN NOT NULL DEFAULT false,
    "os" TEXT,
    "verified" BOOLEAN NOT NULL DEFAULT false,
    "instance_id" TEXT,
    "aud" TEXT,
    "encrypted_password" TEXT,
    "confirmation_token" TEXT,
    "confirmation_sent_at" DATETIME,
    "raw_app_meta_data" JSONB,
    "raw_user_meta_data" JSONB,
    "banned_until" DATETIME,
    "deleted_at" DATETIME,
    "invited_at" DATETIME,
    "last_visit" DATETIME,
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" DATETIME NOT NULL,
    "first_visit" DATETIME,
    "confirmed_at" DATETIME,
    "last_login_at" DATETIME,
    "last_sign_in_at" DATETIME
);

-- CreateIndex
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");
