export type UserType = {
  id: string;
  sex: string;
  name: string;
  avatar: string;
  zipCode: string;
  verified: boolean;
  password: string;
  displayName: string;
  // Email
  email: string;
  email_change: string;
  emailVisibility: boolean;
  emailVerified: boolean;
  emailVerificationToken: string;
  emailVerificationSentAt: string;
  email_change_sent_at: string;
  email_change_token_new: string;
  email_change_confirm_status: number;
  email_change_token_current: string;
  email_confirmed_at: string;
  // Token
  encrypted_password: string;
  reauthentication_token: string;
  reauthentication_sent_at: string;
  recovery_token: string;
  recovery_sent_at: string;
  confirmation_token: string;
  confirmation_sent_at: string;
  // Roll
  is_super_admin: boolean;
  is_sso_user: boolean;
  is_anonymous: boolean;
  // Phone
  phone: string;
  phone_change: string;
  phone_change_token: string;
  phone_change_sent_at: string;
  phone_confirmed_at: string;
  verificationCode: string;
  verificationCodeSentAt: string;
  phoneVerified: boolean;
  // Agent
  browser: string;
  device: string;
  online: boolean;
  os: string;
  // App
  instance_id: string;
  aud: string;
  raw_app_meta_data: object;
  raw_user_meta_data: object;
  // Date
  banned_until: string;
  deleted_at: string;
  invited_at: string;
  last_visit: string;
  created_at: string;
  updated_at: string;
  first_visit: string;
  confirmed_at: string;
  last_login_at: string;
  last_sign_in_at: string;
  Website: [];
  Retention: [];
};
